"""
Revenue and income variables for UAE corporate tax.
"""

from dgce_model.openfisca_core.model_api import *
from dgce_model.entities import Business


class revenue(Variable):
    value_type = float
    entity = Business
    definition_period = YEAR
    label = "Total business revenue"
    reference = "Federal Decree-Law No. 47 of 2022, Article 20"
    documentation = """
    Total revenue generated by the business from all sources during the tax period.
    This includes:
    - Sales of goods and services
    - Investment income
    - Other operating income
    - Gains from disposal of assets
    """


class cost_of_goods_sold(Variable):
    value_type = float
    entity = Business
    definition_period = YEAR
    label = "Cost of goods sold"
    documentation = """
    Direct costs attributable to the production of goods sold by the business.
    """


class operating_expenses(Variable):
    value_type = float
    entity = Business
    definition_period = YEAR
    label = "Operating expenses"
    documentation = """
    General operating expenses including:
    - Salaries and wages
    - Rent
    - Utilities
    - Administrative expenses
    """


class gross_profit(Variable):
    value_type = float
    entity = Business
    definition_period = YEAR
    label = "Gross profit"
    
    def formula(business, period, parameters):
        revenue = business('revenue', period)
        cogs = business('cost_of_goods_sold', period)
        return revenue - cogs


class accounting_profit(Variable):
    value_type = float
    entity = Business
    definition_period = YEAR
    label = "Accounting profit before tax"
    reference = "Federal Decree-Law No. 47 of 2022, Article 20"
    
    def formula(business, period, parameters):
        gross_profit = business('gross_profit', period)
        operating_expenses = business('operating_expenses', period)
        interest_expense = business('interest_expense', period)
        depreciation = business('depreciation_expense', period)
        other_expenses = business('other_expenses', period)
        
        return gross_profit - operating_expenses - interest_expense - depreciation - other_expenses


class interest_income(Variable):
    value_type = float
    entity = Business
    definition_period = YEAR
    label = "Interest income"
    documentation = "Interest received from loans, deposits, and other financial instruments"


class interest_expense(Variable):
    value_type = float
    entity = Business
    definition_period = YEAR
    label = "Interest expense"
    documentation = "Interest paid on loans and other borrowings"


class depreciation_expense(Variable):
    value_type = float
    entity = Business
    definition_period = YEAR
    label = "Depreciation expense"
    documentation = "Depreciation of tangible and intangible assets"


class other_expenses(Variable):
    value_type = float
    entity = Business
    definition_period = YEAR
    label = "Other expenses"
    documentation = "Miscellaneous business expenses"